### ISSUE TITLE
Experiencing failure in Codepipeline due to "gem install cfn-nag" 

### ISSUE THREAD

**Issue by dghadge** [awslabs/cloudformation-validation-pipeline#10]
Lambda Lint_Template is failing with the following error --
"message": "1 lint failures [[u'TemplateArtifact', 'aws-vpc.template', u'linting of template aws-vpc.template failedError while executing command: gem install cfn-nag. Reason: exit status 1 - COMMAND_EXECUTION_ERROR']]",

**Comment by gsingh04** [comment]
Thanks for your feedback. We are researching the issue at our end and currently working on the next release. For the fix and new release please continue to monitor the repo. 
On investigation it seems the issue was cfn_nag could not be installed. Please update your Lint_Template lambda function with below changes and let us know if it resolves the issue.
```
        build_response = codebuild_client.start_build(projectName='CFN-Lint-' + pipeline_name,
                                                      buildspecOverride="""version: 0.2

phases:
  install:
    commands:
      - apt-get  -y update
      - apt-get -y install ruby-full
      - ruby --version
      - apt-get install gcc make -y
      - apt-get -y install jq
      - gem install cfn-nag""" + cfn_nag_version + """
```
